version: "3"

networks:

  nodeNet:
    name: nodeNet
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"

services:
  container1:
    image: fir.love.io:3005/nettools:latest
    container_name: container1
    networks:
      nodeNet:
        ipv4_address: 192.168.1.200

  container2:
    image: fir.love.io:3005/nettools:latest
    container_name: container2
    networks:
      nodeNet:
        ipv4_address: 192.168.1.201